version: "3"
services:
  mysql-db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 2

  api-server:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
